easy_admin:
    entities:
        Shiftment:
            class: 'KejawenLab\Application\SemartHris\Entity\Shiftment'
            controller: 'EasyCorp\Bundle\EasyAdminBundle\Controller\AdminController'
            templates:
                new: 'app/shiftment/new.html.twig'
                edit: 'app/shiftment/edit.html.twig'
            new:
                title: 'Tambah Shift Kerja'
            edit:
                title: 'Edit Shift Kerja'
            search:
                title: 'Shift Kerja'
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'code', label: 'Kode Shift' }
                    - { property: 'name', label: 'Nama Shift' }
                    - { type: 'group', css_class: 'col-sm-3' }
                    - { property: 'startHour', label: 'Jam Masuk', type_options:{ attr: { class: 'time-picker' }, widget: 'single_text' } }
                    - { type: 'group', css_class: 'col-sm-3' }
                    - { property: 'endHour', label: 'Jam Pulang', type_options:{ attr: { class: 'time-picker' }, widget: 'single_text' } }
            show:
                title: 'Detil Shift Kerja'
                fields:
                    - { property: 'code', label: 'Kode Shift' }
                    - { property: 'name', label: 'Nama Shift' }
                    - { property: 'startHour', label: 'Kode Shift' }
                    - { property: 'endHour', label: 'Nama Shift' }
            list:
                title: 'Shift Kerja'
                fields:
                    - { property: 'code', label: 'Kode Shift' }
                    - { property: 'name', label: 'Nama Shift' }
                    - { property: 'startHour', label: 'Kode Shift' }
                    - { property: 'endHour', label: 'Nama Shift' }

        Workshift:
            class: 'KejawenLab\Application\SemartHris\Entity\Workshift'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\WorkshiftController'
            disabled_actions: ['search', 'show']
            templates:
                new: 'app/workshift/new.html.twig'
                list: 'app/workshift/list.html.twig'
                edit: 'app/workshift/edit.html.twig'
            new:
                title: 'Tambah Jadwal Kerja'
            edit:
                title: 'Edit Jadwal Kerja'
            search:
                title: 'Jadwal Kerja'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'employee', label: 'Karyawan', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'shiftment', label: 'Shift Kerja', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6 new-row' }
                    - { property: 'startDate', label: 'Dari Tanggal', type_options:{ format: 'dd-MM-yyyy', attr: { class: 'date-picker' }, widget: 'single_text' } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'endDate', label: 'Sampai Tanggal', type_options:{ format: 'dd-MM-yyyy', attr: { class: 'date-picker' }, widget: 'single_text' } }
                    - { type: 'group', css_class: 'col-sm-12 new-row' }
                    - { property: 'description', label: 'Keterangan' }
            list:
                title: 'Jadwal Kerja'
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'startDate', label: 'Dari Tanggal' }
                    - { property: 'endDate', label: 'Sampai Tanggal' }
                    - { property: 'shiftment.startHour', label: 'Jam Masuk', type: 'time' }
                    - { property: 'shiftment.endHour', label: 'Jam Pulang', type: 'time' }
                    - { property: 'description', label: 'Keterangan' }

        Attendance:
            class: 'KejawenLab\Application\SemartHris\Entity\Attendance'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AttendanceController'
            disabled_actions: ['search']
            templates:
                new: 'app/attendance/new.html.twig'
                list: 'app/attendance/list.html.twig'
                edit: 'app/attendance/edit.html.twig'
            new:
                title: 'Tambah Presensi'
            edit:
                title: 'Edit Presensi'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'employee', label: 'Karyawan', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'attendanceDate', label: 'Tanggal', type_options:{ format: 'dd-MM-yyyy', attr: { class: 'date-picker' }, widget: 'single_text' } }
                    - { type: 'group', css_class: 'col-sm-6 new-row' }
                    - { property: 'checkIn', label: 'Jam Masuk', type_options:{ attr: { class: 'time-picker' }, widget: 'single_text' } }
                    - { property: 'checkOut', label: 'Jam Keluar', type_options:{ attr: { class: 'time-picker' }, widget: 'single_text' } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'absent', label: 'Tidak Masuk?' }
                    - { property: 'reason', type: 'hidden', type_options: { attr: { class: 'reason-id' } } }
                    - { property: 'reason_readonly', label: 'Alasan', type: 'text', type_options: { mapped: false, attr: { readonly: true } } }
                    - { property: 'reason_text', label: 'Alasan', type: 'choice', type_options: { attr: { class: 'reason-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { type: 'group', css_class: 'col-sm-12 new-row' }
                    - { property: 'description', label: 'Keterangan' }
            show:
                title: 'Detil Presensi'
                fields:
                    - { property: 'attendanceDate', label: 'Tanggal' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'shiftment', label: 'Shift' }
                    - { property: 'checkIn', label: 'Jam Masuk' }
                    - { property: 'checkOut', label: 'Jam Keluar' }
                    - { property: 'earlyIn', label: 'Masuk Lebih Awal', help: 'Dalam menit' }
                    - { property: 'lateIn', label: 'Terlambat', help: 'Dalam menit' }
                    - { property: 'earlyOut', label: 'Pulang Cepat', help: 'Dalam menit' }
                    - { property: 'lateOut', label: 'Pulang Lebih Lama', help: 'Dalam menit' }
                    - { property: 'absent', label: 'Tidak Masuk?' }
                    - { property: 'reason', label: 'Alasan' }
                    - { property: 'description', label: 'Keterangan' }
            list:
                title: 'Presensi'
                fields:
                    - { property: 'attendanceDate', label: 'Tanggal' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'shiftment', label: 'Shift' }
                    - { property: 'checkIn', label: 'Jam Masuk' }
                    - { property: 'checkOut', label: 'Jam Keluar' }
                    - { property: 'absent', label: 'Tidak Masuk?' }
                    - { property: 'reason', label: 'Alasan' }
                    - { property: 'description', label: 'Keterangan' }
