easy_admin:
    entities:
        City:
            class: 'KejawenLab\Application\SemarHris\Entity\City'
            controller: 'KejawenLab\Application\SemarHris\Controller\Admin\CityController'
            new:
                title: 'Tambah Kota'
            edit:
                title: 'Edit Kota'
            search:
                title: 'Kota'
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', label: 'Informasi Kota', icon: 'book', css_class: 'col-sm-12' }
                    - { property: 'region', label: 'Pripinsi', type: 'easyadmin_autocomplete' }
                    - { property: 'code', label: 'Kode Kota' }
                    - { property: 'name', label: 'Nama Kota' }
            show:
                title: 'Detil Kota'
                fields:
                    - { property: 'region', label: 'Pripinsi' }
                    - { property: 'code', label: 'Kode Kota' }
                    - { property: 'name', label: 'Nama Kota' }
            list:
                title: 'Kota'
                fields:
                    - { property: 'region', label: 'Pripinsi' }
                    - { property: 'code', label: 'Kode Kota' }
                    - { property: 'name', label: 'Nama Kota' }

        Region:
            class: 'KejawenLab\Application\SemarHris\Entity\Region'
            new:
                title: 'Tambah Propinsi'
            edit:
                title: 'Edit Propinsi'
            search:
                title: 'Propinsi'
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', label: 'Informasi Propinsi', icon: 'book', css_class: 'col-sm-12' }
                    - { property: 'code', label: 'Kode Propinsi' }
                    - { property: 'name', label: 'Nama Propinsi' }
            show:
                title: 'Detil Propinsi'
                fields:
                    - { property: 'code', label: 'Kode Propinsi' }
                    - { property: 'name', label: 'Nama Propinsi' }
            list:
                title: 'Propinsi'
                fields:
                    - { property: 'code', label: 'Kode Propinsi' }
                    - { property: 'name', label: 'Nama Propinsi' }