easy_admin:
    entities:
        City:
            role: 'ROLE_HRSTAFF'
            class: 'KejawenLab\Application\SemartHris\Entity\City'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\CityController'
            new:
                title: 'Tambah Kota'
            edit:
                title: 'Edit Kota'
            search:
                title: 'Kota'
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12' }
                    - { property: 'region', label: 'Pripinsi', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'code', label: 'Kode Kota' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Nama Kota' }
            show:
                title: 'Detil Kota'
                fields:
                    - { property: 'region', label: 'Pripinsi' }
                    - { property: 'code', label: 'Kode Kota' }
                    - { property: 'name', label: 'Nama Kota' }
            list:
                role: 'ROLE_HRSTAFF'
                title: 'Kota'
                fields:
                    - { property: 'region', label: 'Pripinsi' }
                    - { property: 'code', label: 'Kode Kota' }
                    - { property: 'name', label: 'Nama Kota' }

        Region:
            role: 'ROLE_HRSTAFF'
            class: 'KejawenLab\Application\SemartHris\Entity\Region'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            new:
                title: 'Tambah Propinsi'
            edit:
                title: 'Edit Propinsi'
            search:
                title: 'Propinsi'
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'code', label: 'Kode Propinsi' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Nama Propinsi' }
            show:
                title: 'Detil Propinsi'
                fields:
                    - { property: 'code', label: 'Kode Propinsi' }
                    - { property: 'name', label: 'Nama Propinsi' }
            list:
                role: 'ROLE_HRSTAFF'
                title: 'Propinsi'
                fields:
                    - { property: 'code', label: 'Kode Propinsi' }
                    - { property: 'name', label: 'Nama Propinsi' }
