easy_admin:
    entities:
        Company:
            class: 'Persona\Hris\Entity\Company'
            new:
                title: 'Tambah Perusahaan'
            edit:
                title: 'Edit Perusahaan'
            search:
                title: 'Perusahaan'
                fields: ['code', 'name']
            form:
                fields:
                    - { property: 'parent', label: 'Perusahaan Induk', type: 'easyadmin_autocomplete' }
                    - { property: 'code', label: 'Kode Perusahaan' }
                    - { property: 'name', label: 'Nama Perusahaan' }
                    - { property: 'birthDay', label: 'Tanggal Berdiri' }
                    - { property: 'email', label: 'Alamat Email' }
                    - { property: 'taxNumber', label: 'NPWP' }
            show:
                title: 'Detil Perusahaan'
                fields:
                    - { property: 'parent', label: 'Perusahaan Induk' }
                    - { property: 'code', label: 'Kode Perusahaan' }
                    - { property: 'name', label: 'Nama Perusahaan' }
                    - { property: 'birthDay', label: 'Tanggal Berdiri' }
                    - { property: 'email', label: 'Alamat Email' }
                    - { property: 'taxNumber', label: 'NPWP' }
            list:
                title: 'Perusahaan'
                actions:
                    - { name: 'company_department', type: 'route', icon: 'university', label: false }
                    - { name: 'company_address', type: 'route', icon: 'book', label: false }
                fields:
                    - { property: 'parent', label: 'Perusahaan Induk' }
                    - { property: 'code', label: 'Kode Perusahaan' }
                    - { property: 'name', label: 'Nama Perusahaan' }

        CompanyDepartment:
            class: 'Persona\Hris\Entity\CompanyDepartment'
            controller: 'Persona\Hris\Controller\Admin\CompanyDepartmentController'
            disabled_actions: ['search']
            new:
                title: 'Tambah Departemen Perusahaan'
            edit:
                title: 'Edit Departemen Perusahaan'
            form:
                fields:
                    - { property: 'company', type: 'hidden' }
                    - { property: 'company_text', label: 'Perusahaan', type: 'text', type_options: { mapped: false, attr: { readonly: true } }  }
                    - { property: 'department', label: 'Departemen' }
            show:
                title: 'Detil Departemen Perusahaan'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'department', label: 'Departemen' }
            list:
                title: 'Departemen Perusahaan'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'department', label: 'Departemen' }

        CompanyAddress:
            class: 'Persona\Hris\Entity\CompanyAddress'
            controller: 'Persona\Hris\Controller\Admin\CompanyAddressController'
            disabled_actions: ['search']
            new:
                title: 'Tambah Alamat Perusahaan'
            edit:
                title: 'Edit Alamat Perusahaan'
            form:
                fields:
                    - { property: 'company', type: 'hidden' }
                    - { property: 'company_text', label: 'Perusahaan', type: 'text', type_options: { mapped: false, attr: { readonly: true } }  }
                    - { property: 'address', label: 'Alamat' }
                    - { property: 'region', label: 'Propinsi', type: 'easyadmin_autocomplete' }
                    - { property: 'city', label: 'Kota', type: 'easyadmin_autocomplete' }
                    - { property: 'postalCode', label: 'Kode Pos' }
                    - { property: 'phoneNumber', label: 'No. Telpon' }
                    - { property: 'faxNumber', label: 'No. Fax' }
            show:
                title: 'Detil Alamat Perusahaan'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'address', label: 'Alamat' }
                    - { property: 'city', label: 'Kota' }
                    - { property: 'region', label: 'Propinsi' }
                    - { property: 'postalCode', label: 'Kode Pos' }
                    - { property: 'phoneNumber', label: 'No. Telpon' }
                    - { property: 'faxNumber', label: 'No. Fax' }
            list:
                title: 'Alamat Perusahaan'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'address', label: 'Alamat' }
                    - { property: 'city', label: 'Kota' }
                    - { property: 'region', label: 'Propinsi' }
                    - { property: 'postalCode', label: 'Kode Pos' }