easy_admin:
    entities:
        Company:
            role: 'ROLE_HRSTAFF'
            class: 'KejawenLab\Application\SemartHris\Entity\Company'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\CompanyController'
            new:
                title: 'Tambah Perusahaan'
            edit:
                title: 'Edit Perusahaan'
            search:
                title: 'Perusahaan'
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12' }
                    - { property: 'parent', label: 'Perusahaan Induk', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6 new-row' }
                    - { property: 'code', label: 'Kode Perusahaan' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Nama Perusahaan' }
                    - { type: 'group', css_class: 'col-sm-4 new-row' }
                    - { property: 'birthDay', label: 'Tanggal Berdiri', type: 'birthday', type_options: { placeholder: { year: 'Tahun', month: 'Bulan', day: 'Tanggal' } } }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'email', label: 'Email' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'taxNumber', label: 'NPWP' }
            show:
                title: 'Detil Perusahaan'
                fields:
                    - { property: 'parent', label: 'Perusahaan Induk' }
                    - { property: 'code', label: 'Kode Perusahaan' }
                    - { property: 'name', label: 'Nama Perusahaan' }
                    - { property: 'birthDay', label: 'Tanggal Berdiri' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'address.address', label: 'Alamat'}
                    - { property: 'address.city', label: 'Kota'}
                    - { property: 'address.region', label: 'Propinsi'}
                    - { property: 'address.postalCode', label: 'Kode Pos'}
                    - { property: 'address.phoneNumber', label: 'No. Telpon'}
                    - { property: 'address.faxNumber', label: 'No. Fax'}
                    - { property: 'taxNumber', label: 'NPWP' }
            list:
                role: 'ROLE_HRSTAFF'
                title: 'Perusahaan'
                actions:
                    - { name: 'company_department', type: 'route', icon: 'university', label: false, title: 'Lihat Department' }
                    - { name: 'company_address', type: 'route', icon: 'book', label: false, title: 'Lihat Alamat' }
                fields:
                    - { property: 'parent', label: 'Perusahaan Induk' }
                    - { property: 'code', label: 'Kode Perusahaan' }
                    - { property: 'name', label: 'Nama Perusahaan' }

        Department:
            role: 'ROLE_HRSTAFF'
            class: 'KejawenLab\Application\SemartHris\Entity\Department'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\DepartmentController'
            new:
                title: 'Tambah Departemen'
            edit:
                title: 'Edit Departemen'
            search:
                title: 'Departemen'
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12' }
                    - { property: 'parent', label: 'Departemen Induk', type: 'easyadmin_autocomplete' }
                    - { type: 'group', css_class: 'col-sm-6 new-row' }
                    - { property: 'code', label: 'Kode Departemen' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Nama Departemen' }
            show:
                title: 'Detil Departemen'
                fields:
                    - { property: 'parent', label: 'Departemen Induk' }
                    - { property: 'code', label: 'Kode Departemen' }
                    - { property: 'name', label: 'Nama Departemen' }
            list:
                role: 'ROLE_HRSTAFF'
                title: 'Departemen'
                fields:
                    - { property: 'parent', label: 'Departemen Induk' }
                    - { property: 'code', label: 'Kode Departemen' }
                    - { property: 'name', label: 'Nama Departemen' }

        CompanyDepartment:
            role: 'ROLE_HRSTAFF'
            class: 'KejawenLab\Application\SemartHris\Entity\CompanyDepartment'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\CompanyDepartmentController'
            disabled_actions: ['search']
            new:
                title: 'Tambah Departemen Perusahaan'
            edit:
                title: 'Edit Departemen Perusahaan'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'company', type: 'hidden' }
                    - { property: 'company_readonly', label: 'Perusahaan', type: 'text', type_options: { mapped: false, attr: { readonly: true } }  }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'department', label: 'Departemen' }
            show:
                title: 'Detil Departemen Perusahaan'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'department', label: 'Departemen' }
            list:
                role: 'ROLE_HRSTAFF'
                title: 'Departemen Perusahaan'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'department', label: 'Departemen' }

        CompanyAddress:
            role: 'ROLE_HRSTAFF'
            class: 'KejawenLab\Application\SemartHris\Entity\CompanyAddress'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\CompanyAddressController'
            templates:
                new: 'app/address/new.html.twig'
                edit: 'app/address/edit.html.twig'
                list: 'app/address/list.html.twig'
            new:
                title: 'Tambah Alamat Perusahaan'
            edit:
                title: 'Edit Alamat Perusahaan'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12' }
                    - { property: 'company', label: 'Perusahaan', type: 'easyadmin_autocomplete' }
                    - { property: 'company_readonly', label: 'Perusahaan', type: 'text', type_options: { mapped: false, attr: { readonly: true } } }
                    - { property: 'address', label: 'Alamat' }
                    - { property: 'defaultAddress', label: 'Set Default' }
                    - { type: 'group', css_class: 'col-sm-6 new-row' }
                    - { property: 'region', label: 'Propinsi', type: 'easyadmin_autocomplete', type_options: { attr: { class: 'region-select' } } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'city', type: 'hidden', type_options: { attr: { class: 'city-id' } } }
                    - { property: 'city_text', label: 'Kota', type: 'choice', type_options: { attr: { class: 'city-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { type: 'group', css_class: 'col-sm-4 new-row' }
                    - { property: 'postalCode', label: 'Kode Pos' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'phoneNumber', label: 'No. Telpon' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'faxNumber', label: 'No. Fax' }
            show:
                title: 'Detil Alamat Perusahaan'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'address', label: 'Alamat' }
                    - { property: 'city', label: 'Kota' }
                    - { property: 'region', label: 'Propinsi' }
                    - { property: 'postalCode', label: 'Kode Pos' }
                    - { property: 'phoneNumber', label: 'No. Telpon' }
                    - { property: 'faxNumber', label: 'No. Fax' }
                    - { property: 'defaultAddress', label: 'Set Default' }
            list:
                role: 'ROLE_HRSTAFF'
                title: 'Alamat Perusahaan'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'address', label: 'Alamat' }
                    - { property: 'city', label: 'Kota' }
                    - { property: 'region', label: 'Propinsi' }
                    - { property: 'postalCode', label: 'Kode Pos' }
                    - { property: 'defaultAddress', label: 'Default' }
