easy_admin:
    entities:
        Contract:
            class: 'KejawenLab\Application\SemartHris\Entity\Contract'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\ContractController'
            templates:
                new: '/app/contract/new.html.twig'
                edit: '/app/contract/edit.html.twig'
            new:
                title: 'Tambah Kontrak'
            edit:
                title: 'Edit Kontrak'
            search:
                title: 'Kontrak'
                fields: ['letterNumber', 'tags']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'type', label: 'Tipe Kontrak', type: 'choice', type_options: { attr: { class: 'static-select' }, choices: { 'label.form.empty_value': '', 'KONTRAK KARYAWAN': 'e', 'KONTRAK REKANAN/KLIEN': 'c' } } }
                    - { property: 'letterNumber', label: 'No. Kontrak' }
                    - { property: 'subject', label: 'Subyek' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'startDate', label: 'Tanggal Awal' }
                    - { property: 'endDate', label: 'Tanggal Akhir' }
                    - { property: 'signedDate', label: 'Tanggal Tanda Tangan' }
                    - { type: 'group', css_class: 'col-sm-12' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'tags', type: 'hidden', type_options: { attr: { class: 'tags-id' } } }
                    - { property: 'tags_text', label: 'Penanda', help: 'Tekan Enter untuk menambahkan tag', type: 'choice', type_options: { attr: { class: 'tags-select', multiple: 'multiple' }, mapped: false, placeholder: false } }
            show:
                title: 'Detil Kontrak'
                fields:
                    - { property: 'type_text', label: 'Tipe Kontrak' }
                    - { property: 'letterNumber', label: 'No. Kontrak' }
                    - { property: 'subject', label: 'Subyek' }
                    - { property: 'startDate', label: 'Tanggal Awal' }
                    - { property: 'endDate', label: 'Tanggal Akhir' }
                    - { property: 'signedDate', label: 'Tanggal Tanda Tangan' }
                    - { property: 'description', label: 'Description' }
                    - { property: 'tags', label: 'Penanda', template: '/app/default/field_array.html.twig' }
            list:
                title: 'Kontrak'
                fields:
                    - { property: 'type_text', label: 'Tipe Kontrak' }
                    - { property: 'letterNumber', label: 'No. Kontrak' }
                    - { property: 'subject', label: 'Subyek' }
                    - { property: 'startDate', label: 'Tanggal Awal' }
                    - { property: 'endDate', label: 'Tanggal Akhir' }
                    - { property: 'signedDate', label: 'Tanggal Tanda Tangan' }
