easy_admin:
    entities:
        Department:
            class: 'KejawenLab\Application\SemarHris\Entity\Department'
            new:
                title: 'Tambah Departemen'
            edit:
                title: 'Edit Departemen'
            search:
                title: 'Departemen'
                fields: ['code', 'name']
            form:
                fields:
                    - { property: 'parent', label: 'Departemen Induk', type: 'easyadmin_autocomplete' }
                    - { property: 'code', label: 'Kode Departemen' }
                    - { property: 'name', label: 'Nama Departemen' }
            show:
                title: 'Detil Departemen'
                fields:
                    - { property: 'parent', label: 'Departemen Induk' }
                    - { property: 'code', label: 'Kode Departemen' }
                    - { property: 'name', label: 'Nama Departemen' }
            list:
                title: 'Departemen'
                fields:
                    - { property: 'parent', label: 'Departemen Induk' }
                    - { property: 'code', label: 'Kode Departemen' }
                    - { property: 'name', label: 'Nama Departemen' }