easy_admin:
    entities:
        Employee:
            class: 'KejawenLab\Application\SemartHris\Entity\Employee'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\EmployeeController'
            templates:
                new: 'app/employee/new.html.twig'
                edit: 'app/employee/edit.html.twig'
                list: 'app/employee/list.html.twig'
            new:
                title: 'Tambah Karyawan'
            edit:
                title: 'Edit Karyawan'
            search:
                title: 'Karyawan'
                fields: ['code', 'fullName']
            form:
                fields:
                    - { type: 'group', icon: 'user-md', label: 'Data Pribadi', css_class: 'col-sm-6' }
                    - { property: 'code', label: 'Kode Karyawan' }
                    - { property: 'fullName', label: 'Nama Karyawan' }
                    - { property: 'gender', label: 'Jenis Kelamin', type: 'choice', type_options: { attr: { class: 'static-select' }, choices: { 'label.form.empty_value': '', PRIA: 'm', WANITA: 'f' } } }
                    - { property: 'regionOfBirth', label: 'Propinsi Kelahiran', type: 'easyadmin_autocomplete', type_options: { attr: { class: 'region-select' } } }
                    - { property: 'cityOfBirth', type: 'hidden', type_options: { attr: { class: 'city-id' } } }
                    - { property: 'city_text', label: 'Kota Kelahiran', type: 'choice', type_options: { attr: { class: 'city-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { property: 'dateOfBirth', label: 'Tanggal Lahir', type: 'birthday' }
                    - { property: 'identityType', label: 'Jenis Identitas', type: 'choice', type_options: { attr: { class: 'static-select' }, choices: { 'label.form.empty_value': '', SIM: 's', PASPOR: 'p', 'KTP': 'k' } } }
                    - { property: 'identityNumber', label: 'No. Identitas' }
                    - { property: 'maritalStatus', label: 'Status Perkawinan', type: 'choice', type_options: { attr: { class: 'static-select' }, choices: { 'label.form.empty_value': '', 'BELUM MENIKAH': 's', 'MENIKAH': 'm', 'CERAI': 'd' } } }
                    - { property: 'email', label: 'Alamat Email' }
                    - { property: 'taxGroup', label: 'Kode Pajak', type: 'choice', type_options: { attr: { class: 'static-select' }, choices: { 'label.form.empty_value': '', TK0: 'tk0', TK1: 'tk1', TK2: 'tk2', TK3: 'tk3', K0: 'k0', K1: 'k1', K2: 'k2', K3: 'k3', KI0: 'ki0', KI1: 'ki1', KI2: 'ki2', KI3: 'ki3' } } }
                    - { property: 'haveOvertimeBenefit', label: 'Berhak Lembur?', type_options: { required: false } }
                    - { type: 'group', icon: 'id-card-o', label: 'Informasi Perusahaan', css_class: 'col-sm-6' }
                    - { property: 'employeeStatus', label: 'Status Karyawan', type: 'choice', type_options: { attr: { class: 'static-select' }, choices: { 'label.form.empty_value': '', 'KARYAWAN TETAP': 'p', 'KARYAWAN KONTRAK': 't', 'KARYAWAN OUTSOURCE': 'o', 'KARYAWAN MAGANG': 'i' } } }
                    - { property: 'contract', type: 'hidden', type_options: { attr: { class: 'contract-id' } } }
                    - { property: 'contract_text', label: 'Kontrak Kerja', type: 'choice', type_options: { attr: { class: 'contract-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { property: 'company', label: 'Perusahaan', type: 'easyadmin_autocomplete', type_options: { attr: { class: 'company-select' } } }
                    - { property: 'company_readonly', label: 'Perusahaan', type: 'text', type_options: { mapped: false, attr: { readonly: true } } }
                    - { property: 'department', type: 'hidden', type_options: { attr: { class: 'department-id' } } }
                    - { property: 'department_readonly', label: 'Department', type: 'text', type_options: { mapped: false, attr: { readonly: true } } }
                    - { property: 'department_text', label: 'Department', type: 'choice', type_options: { attr: { class: 'department-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { property: 'jobLevel', label: 'Level Jabatan', type: 'easyadmin_autocomplete', type_options: { attr: { class: 'joblevel-select' } } }
                    - { property: 'joblevel_readonly', label: 'Level Jabatan', type: 'text', type_options: { mapped: false, attr: { readonly: true } } }
                    - { property: 'jobTitle', type: 'hidden', type_options: { attr: { class: 'jobtitle-id' } } }
                    - { property: 'jobtitle_readonly', label: 'Jabatan', type: 'text', type_options: { mapped: false, attr: { readonly: true } } }
                    - { property: 'jobtitle_text', label: 'Jabatan', type: 'choice', type_options: { attr: { class: 'jobtitle-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { property: 'supervisor', type: 'hidden', type_options: { attr: { class: 'supervisor-id' }, required: false } }
                    - { property: 'supervisor_readonly', label: 'Atasan Langsung', type: 'text', type_options: { mapped: false, attr: { readonly: true } } }
                    - { property: 'supervisor_text', label: 'Atasan Langsung', type: 'choice', type_options: { attr: { class: 'supervisor-select' }, required: false, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { property: 'supervisor_empty', label: 'Atasan Langsung', type: 'text', type_options: { attr: { readonly: true }, mapped: false } }
            show:
                title: 'Detil Karyawan'
                fields:
                    - { property: 'code', label: 'Kode Karyawan' }
                    - { property: 'fullName', label: 'Nama Karyawan' }
                    - { property: 'joinDate', label: 'Tanggal Masuk' }
                    - { property: 'employee_status_text', label: 'Status Karyawan' }
                    - { property: 'contract.letterNumber', label: 'No. Kontrak' }
                    - { property: 'contract.EndDate', label: 'Tanggal Akhir Kontrak' }
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'department', label: 'Department' }
                    - { property: 'jobLevel', label: 'Level Jabatan' }
                    - { property: 'jobTitle', label: 'Jabatan' }
                    - { property: 'supervisor', label: 'Atasan Langsung' }
                    - { property: 'haveOvertimeBenefit', label: 'Berhak Lembur?' }
                    - { property: 'tax_group_text', label: 'Kode Pajak' }
                    - { property: 'gender_text', label: 'Jenis Kelamin' }
                    - { property: 'marital_status_text', label: 'Status Perkawinan' }
                    - { property: 'identity_type_text', label: 'Jenis Identitas' }
                    - { property: 'identityNumber', label: 'No. Identitas' }
                    - { property: 'regionOfBirth', label: 'Propinsi Kelahiran' }
                    - { property: 'cityOfBirth', label: 'Kota Kelahiran' }
                    - { property: 'dateOfBirth', label: 'Tanggal Lahir' }
                    - { property: 'address.address', label: 'Alamat'}
                    - { property: 'address.city', label: 'Kota'}
                    - { property: 'address.region', label: 'Propinsi'}
                    - { property: 'address.postalCode', label: 'Kode Pos'}
                    - { property: 'address.phoneNumber', label: 'No. Telpon'}
                    - { property: 'address.faxNumber', label: 'No. Fax'}
                    - { property: 'email', label: 'Alamat Email' }
            list:
                title: 'Karyawan'
                actions:
                    - { name: 'employee_address', type: 'route', icon: 'book', label: false }
                fields:
                    - { property: 'code', label: 'Kode Karyawan' }
                    - { property: 'fullName', label: 'Nama Karyawan' }
                    - { property: 'gender_text', label: 'Jenis Kelamin' }
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'jobTitle', label: 'Jabatan' }
                    - { property: 'joinDate', label: 'Tanggal Masuk' }
                    - { property: 'employee_status_text', label: 'Status' }
                    - { property: 'supervisor', label: 'Atasan' }
                    - { property: 'resign', label: 'Resign?', type: 'boolean' }
                    - { property: 'haveOvertimeBenefit', label: 'Hak Lembur?', type: 'boolean' }

        EmployeeAddress:
            class: 'KejawenLab\Application\SemartHris\Entity\EmployeeAddress'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\EmployeeAddressController'
            templates:
                new: 'app/address/new.html.twig'
                edit: 'app/address/edit.html.twig'
                list: 'app/address/list.html.twig'
            new:
                title: 'Tambah Alamat Karyawan'
            edit:
                title: 'Edit Alamat Karyawan'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-12' }
                    - { property: 'employee', label: 'Karyawan', type: 'easyadmin_autocomplete' }
                    - { property: 'employee_readonly', label: 'Karyawan', type: 'text', type_options: { mapped: false, attr: { readonly: true } } }
                    - { property: 'address', label: 'Alamat' }
                    - { property: 'defaultAddress', label: 'Set Default' }
                    - { type: 'group', css_class: 'col-sm-6 new-row' }
                    - { property: 'region', label: 'Propinsi', type: 'easyadmin_autocomplete', type_options: { attr: { class: 'region-select' } } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'city', type: 'hidden', type_options: { attr: { class: 'city-id' } } }
                    - { property: 'city_text', label: 'Kota', type: 'choice', type_options: { attr: { class: 'city-select' }, mapped: false, choices: { 'label.form.empty_value': '' } } }
                    - { type: 'group', css_class: 'col-sm-4 new-row' }
                    - { property: 'postalCode', label: 'Kode Pos' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'phoneNumber', label: 'No. Telpon' }
                    - { type: 'group', css_class: 'col-sm-4' }
                    - { property: 'faxNumber', label: 'No. Fax' }
            show:
                title: 'Detil Alamat Karyawan'
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'address', label: 'Alamat' }
                    - { property: 'city', label: 'Kota' }
                    - { property: 'region', label: 'Propinsi' }
                    - { property: 'postalCode', label: 'Kode Pos' }
                    - { property: 'phoneNumber', label: 'No. Telpon' }
                    - { property: 'faxNumber', label: 'No. Fax' }
                    - { property: 'defaultAddress', label: 'Set Default' }
            list:
                title: 'Alamat Karyawan'
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'address', label: 'Alamat' }
                    - { property: 'city', label: 'Kota' }
                    - { property: 'region', label: 'Propinsi' }
                    - { property: 'postalCode', label: 'Kode Pos' }
                    - { property: 'defaultAddress', label: 'Default' }
