easy_admin:
    entities:
        Holiday:
            role: 'ROLE_HRSTAFF'
            class: 'KejawenLab\Application\SemartHris\Entity\Holiday'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            templates:
                new: 'app/holiday/new.html.twig'
                edit: 'app/holiday/edit.html.twig'
            new:
                title: 'Tambah Hari Libur'
            edit:
                title: 'Edit Hari Libur'
            search:
                title: 'Hari Libur'
                fields: ['shortName', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'holidayDate', label: 'Tanggal', type_options: { widget: 'single_text', format: '%env(string:SEMART_DATE_FORMAT_INTL)%', attr: { class: 'date-picker' } } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Nama Libur' }
            show:
                title: 'Detil Hari Libur'
                fields:
                    - { property: 'holidayDate', label: 'Tanggal' }
                    - { property: 'name', label: 'Nama Libur' }
            list:
                role: 'ROLE_HRSTAFF'
                title: 'Hari Libur'
                fields:
                    - { property: 'holidayDate', label: 'Tanggal' }
                    - { property: 'name', label: 'Nama Libur' }
