easy_admin:
    design:
        menu:
            - label: 'Administrator'
              icon: 'shield'
              children:
                  - { entity: 'User', label: 'User', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Setting', label: 'Setting', icon: 'hand-o-right' }
            - label: 'Master'
              icon: 'database'
              children:
                  - { entity: 'EducationalInstitute', label: 'Lembaga Pendidikan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'EducationTitle', label: 'Gelar Pendidikan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'SkillGroup', label: 'Grup Keahlian', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Skill', label: 'Keahlian', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Region', label: 'Propinsi', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'City', label: 'Kota', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Contract', label: 'Kontrak', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Holiday', label: 'Hari Libur', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Perusahaan'
              icon: 'building'
              children:
                  - { entity: 'Company', label: 'Perusahaan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Department', label: 'Departemen', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'JobLevel', label: 'Level Jabatan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'JobTitle', label: 'Jabatan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Karyawan'
              icon: 'user-md'
              children:
                  - { entity: 'Employee', label: 'Profil Karyawan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Placement', label: 'Penempatan Karyawan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Mutation', label: 'Mutasi Karyawan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'CareerHistory', label: 'Riwayat Karir', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Absensi'
              icon: 'clock-o'
              children:
                  - { entity: 'AbsentReason', label: 'Alasan Ketidakhadiran', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Shiftment', label: 'Shift Kerja', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'Workshift', label: 'Jadwal Kerja', icon: 'hand-o-right', params: { sortField: 'startDate', sortDirection: 'DESC' } }
                  - { entity: 'Attendance', label: 'Absensi', icon: 'hand-o-right', params: { sortField: 'attendanceDate', sortDirection: 'DESC' } }
            - label: 'Lembur'
              icon: 'list-alt'
              children:
                  - { entity: 'Overtime', label: 'Lembur', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Cuti'
              icon: 'envelope-o'
              children:
                  - { entity: 'LeaveReason', label: 'Alasan Cuti', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
            - label: 'Alamat'
              icon: 'id-card-o'
              children:
                  - { entity: 'CompanyAddress', label: 'Alamat Perusahaan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
                  - { entity: 'EmployeeAddress', label: 'Alamat Karyawan', icon: 'hand-o-right', params: { sortField: 'createdAt', sortDirection: 'DESC' } }
