easy_admin:
    entities:
        PayrollPeriod:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\PayrollPeriod'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            disabled_actions: ['show', 'new', 'edit', 'delete']
            templates:
                list: 'app/payroll/list.html.twig'
            search:
                title: 'Penggajian'
                fields: ['code', 'name']
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Penggajian'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'year', label: 'Tahun', type: 'text' }
                    - { property: 'month', label: 'Bulan', type: 'text', template: 'app/default/field_month.html.twig' }
                    - { property: 'closed', label: 'Ditutup?' }

        SalaryBenefit:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SalaryBenefit'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\SalaryBenefitController'
            disabled_actions: ['show']
            new:
                title: 'Tambah Tunjangan/Potongan'
            edit:
                title: 'Edit Tunjangan/Potongan'
            search:
                title: 'Tunjangan/Potongan'
            form:
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'component', label: 'Tunjangan/Potongan' }
                    - { property: 'benefitValue', label: 'Nilai', type: 'text' }
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Tunjangan/Potongan'
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'component', label: 'Tunjangan/Potongan' }
                    - { property: 'component.fixed', label: 'Tetap?', type: 'boolean' }
                    - { property: 'benefitValue', label: 'Nilai', type: 'float', template: 'app/default/field_currency.html.twig' }
