easy_admin:
    entities:
        PayrollPeriod:
            role: 'ROLE_HRSTAFF'
            class: 'KejawenLab\Application\SemartHris\Entity\PayrollPeriod'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            disabled_actions: ['show', 'new', 'edit', 'delete']
            search:
                title: 'Period Penggajian'
                fields: ['code', 'name']
            list:
                role: 'ROLE_HRSTAFF'
                title: 'Period Penggajian'
                fields:
                    - { property: 'month', label: 'Bulan' }
                    - { property: 'year', label: 'Tahun' }
                    - { property: 'closed', label: 'Ditutup?' }
