easy_admin:
    entities:
        PayrollPeriod:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\PayrollPeriod'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            disabled_actions: ['show', 'search', 'edit', 'delete']
            templates:
                list: 'app/payroll/list.html.twig'
            search:
                title: 'Penggajian'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Penggajian'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'year', label: 'Tahun', type: 'text' }
                    - { property: 'month', label: 'Bulan', type: 'text', template: 'app/default/field_month.html.twig' }
                    - { property: 'closed', label: 'Ditutup?' }

        SalaryBenefit:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SalaryBenefit'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\SalaryBenefitController'
            disabled_actions: ['show', 'edit', 'delete']
            templates:
                new: 'app/payroll/new.html.twig'
            new:
                title: 'Setting Gaji'
            edit:
                title: 'Setting Gaji'
            search:
                title: 'Setting Gaji'
                fields: ['employee']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'component', label: 'Komponen Gaji' }
                    - { type: 'group', css_class: 'col-sm-12 new-row' }
                    - { property: 'benefitValue', label: 'Nilai', type: 'text', type_options: { attr: { class: 'positive' } } }
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Setting Gaji'
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'component', label: 'Komponen Gaji' }
                    - { property: 'component.fixed', label: 'Tetap?', type: 'boolean' }
                    - { property: 'benefitValue', label: 'Nilai', type: 'float', template: 'app/default/field_currency.html.twig' }

        Payroll:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\Payroll'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\PayrollController'
            disabled_actions: ['show', 'search', 'new', 'edit', 'delete']
            templates:
                list: 'app/payroll/history.html.twig'
            search:
                title: 'Riwayat Penggajian'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Riwayat Penggajian'
                fields:
                    - { property: 'period', label: 'Periode' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'takeHomePay', label: 'Total Gaji', type: 'float', template: 'app/default/field_currency.html.twig' }
