easy_admin:
    entities:
        PayrollPeriod:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\PayrollPeriod'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            disabled_actions: ['show', 'new', 'edit', 'delete']
            templates:
                list: 'app/payroll/list.html.twig'
            search:
                title: 'Penggajian'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Penggajian'
                fields:
                    - { property: 'company', label: 'Perusahaan' }
                    - { property: 'year', label: 'Tahun', type: 'text' }
                    - { property: 'month', label: 'Bulan', type: 'text', template: 'app/default/field_month.html.twig' }
                    - { property: 'closed', label: 'Ditutup?' }

        SalaryBenefit:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SalaryBenefit'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\SalaryBenefitController'
            disabled_actions: ['show']
            templates:
                new: 'app/payroll/new.html.twig'
            new:
                title: 'Setting Gaji'
            edit:
                title: 'Setting Gaji'
            search:
                title: 'Setting Gaji'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'component', label: 'Komponen Gaji' }
                    - { type: 'group', css_class: 'col-sm-12 new-row' }
                    - { property: 'benefitValue', label: 'Nilai', type: 'text', type_options: { attr: { class: 'positive' } } }
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Setting Gaji'
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'component', label: 'Komponen Gaji' }
                    - { property: 'component.fixed', label: 'Tetap?', type: 'boolean' }
                    - { property: 'benefitValue', label: 'Nilai', type: 'float', template: 'app/default/field_currency.html.twig' }

        AttendanceSummary:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\AttendanceSummary'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            disabled_actions: ['show', 'new', 'edit', 'delete']
            search:
                title: 'Riwayat Absensi'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Riwayat Absensi'
                fields:
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'year', label: 'Tahun', type: 'text' }
                    - { property: 'month', label: 'Bulan' }
                    - { property: 'totalWorkday', label: 'Total Hari Kerja' }
                    - { property: 'totalIn', label: 'Total Masuk' }
                    - { property: 'totalLoyality', label: 'Total Loyalitas' }
                    - { property: 'totalAbsent', label: 'Total Tidak Masuk' }
                    - { property: 'totalOvertime', label: 'Total Lembur' }
