easy_admin:
    entities:
        Region:
            class: 'KejawenLab\Application\SemarHris\Entity\Region'
            new:
                title: 'Tambah Propinsi'
            edit:
                title: 'Edit Propinsi'
            search:
                title: 'Propinsi'
                fields: ['code', 'name']
            form:
                fields:
                    - { property: 'code', label: 'Kode Propinsi' }
                    - { property: 'name', label: 'Nama Propinsi' }
            show:
                title: 'Detil Propinsi'
                fields:
                    - { property: 'code', label: 'Kode Propinsi' }
                    - { property: 'name', label: 'Nama Propinsi' }
            list:
                title: 'Propinsi'
                fields:
                    - { property: 'code', label: 'Kode Propinsi' }
                    - { property: 'name', label: 'Nama Propinsi' }