easy_admin:
    entities:
        SalaryComponent:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SalaryComponent'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            templates:
                new: 'app/reason/new.html.twig'
                edit: 'app/reason/edit.html.twig'
            new:
                title: 'Tambah Komponen Gaji'
            edit:
                title: 'Edit Komponen Gaji'
            search:
                title: 'Komponen Gaji'
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'code', label: 'Kode Komponen Gaji' }
                    - { property: 'state', label: 'Tipe', type: 'choice', type_options: { attr: { class: 'static-select' }, choices: { 'label.form.empty_value': '', 'TUNJANGAN': 'p', 'POTONGAN': 'm' } } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Komponen Gaji' }
                    - { property: 'fixed', label: 'Tetap?' }
            show:
                title: 'Detil Komponen Gaji'
                fields:
                    - { property: 'code', label: 'Kode Komponen' }
                    - { property: 'state_text', label: 'Tipe Komponen' }
                    - { property: 'name', label: 'Komponen Gaji' }
                    - { property: 'fixed', label: 'Tetap?' }
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Komponen Gaji'
                fields:
                    - { property: 'code', label: 'Kode Komponen' }
                    - { property: 'state_text', label: 'Tipe Komponen' }
                    - { property: 'name', label: 'Komponen Gaji' }
                    - { property: 'fixed', label: 'Tetap?' }
