easy_admin:
    entities:
        SalaryComponent:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SalaryComponent'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\AdminController'
            templates:
                new: 'app/reason/new.html.twig'
                edit: 'app/reason/edit.html.twig'
            new:
                title: 'Tambah Komponen Gaji'
            edit:
                title: 'Edit Komponen Gaji'
            search:
                title: 'Komponen Gaji'
                fields: ['code', 'name']
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'code', label: 'Kode Komponen Gaji' }
                    - { property: 'state', label: 'Tipe', type: 'choice', type_options: { attr: { class: 'static-select' }, choices: { 'label.form.empty_value': '', 'TUNJANGAN': 'p', 'POTONGAN': 'm' } } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'name', label: 'Komponen Gaji' }
                    - { property: 'fixed', label: 'Tetap?' }
            show:
                title: 'Detil Komponen Gaji'
                fields:
                    - { property: 'code', label: 'Kode Komponen' }
                    - { property: 'state_text', label: 'Tipe Komponen' }
                    - { property: 'name', label: 'Komponen Gaji' }
                    - { property: 'fixed', label: 'Tetap?' }
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Komponen Gaji'
                fields:
                    - { property: 'code', label: 'Kode Komponen' }
                    - { property: 'state_text', label: 'Tipe Komponen' }
                    - { property: 'name', label: 'Komponen Gaji' }
                    - { property: 'fixed', label: 'Tetap?' }

        SalaryAllowancePlus:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SalaryAllowance'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\SalaryAllowanceController'
            disabled_actions: ['search']
            new:
                title: 'Tambah Tunjangan'
            edit:
                title: 'Edit Tunjangan'
            search:
                title: 'Tunjangan'
            form:
                fields:
                    - { property: 'year', label: 'Tahun' }
                    - { property: 'month', label: 'Bulan' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'component', label: 'Komponen Gaji' }
                    - { property: 'benefitValue', label: 'Nilai', type: 'text' }
            show:
                title: 'Detil Tunjangan'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Tunjangan'
                fields:
                    - { property: 'year', label: 'Tahun' }
                    - { property: 'month', label: 'Bulan' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'component', label: 'Tunjangan' }
                    - { property: 'benefitValue', label: 'Nilai' }

        SalaryAllowanceMinus:
            role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
            class: 'KejawenLab\Application\SemartHris\Entity\SalaryAllowance'
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\SalaryAllowanceController'
            disabled_actions: ['search']
            new:
                title: 'Tambah Potongan'
            edit:
                title: 'Edit Potongan'
            search:
                title: 'Potongan'
            form:
            show:
                title: 'Detil Potongan'
            list:
                role: '%env(string:SEMART_SECURITY_PAYROLL_MENU)%'
                title: 'Potongan'
                fields:
                    - { property: 'year', label: 'Tahun' }
                    - { property: 'month', label: 'Bulan' }
                    - { property: 'employee', label: 'Karyawan' }
                    - { property: 'component', label: 'Potongan' }
                    - { property: 'benefitValue', label: 'Nilai' }
