easy_admin:
    entities:
        Setting:
            role: 'ROLE_HRSTAFF'
            class: 'KejawenLab\Application\SemartHris\Entity\Region' #don't use just a config
            controller: 'KejawenLab\Application\SemartHris\Controller\Admin\SettingController'
            disabled_actions: ['show', 'new', 'delete']
            templates:
                edit: 'app/setting/edit.html.twig'
                list: 'app/setting/list.html.twig'
            edit:
                title: 'Edit Konfigurasi'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'code', label: 'Parameter', type_options: { attr: { readonly: true } } }
                    - { type: 'group', css_class: 'col-sm-6' }
                    - { property: 'id', label: 'Nilai Baru' }
            search:
                title: 'Konfigurasi Aplikasi'
            list:
                role: 'ROLE_HRSTAFF'
                title: 'Konfigurasi Aplikasi'
