easy_admin:
    entities:
        SkillGroup:
            class: 'KejawenLab\Application\SemarHris\Entity\SkillGroup'
            new:
                title: 'Tambah Grup Keahlian'
            edit:
                title: 'Edit Grup Keahlian'
            search:
                title: 'Grup Keahlian'
                fields: ['name']
            form:
                fields:
                    - { property: 'parent', label: 'Grup Induk', type: 'easyadmin_autocomplete' }
                    - { property: 'name', label: 'Grup Keahlian' }
            show:
                title: 'Detil Grup Keahlian'
                fields:
                    - { property: 'parent', label: 'GrupInduk' }
                    - { property: 'name', label: 'Grup Keahlian' }
            list:
                title: 'Grup Keahlian'
                fields:
                    - { property: 'parent', label: 'Grup Induk' }
                    - { property: 'name', label: 'Grup Keahlian' }