easy_admin:
    site_name: 'SemarHRIS'
    formats:
        date:     'd-m-Y'
        time:     'H:i'
        datetime: 'd-m-Y H:i:s'
    list:
        max_results: 17
        actions:
            - { name: 'show', icon: 'search', label: false }
            - { name: 'new', icon: 'plus-circle', css_class: 'btn btn-success action-new', label: false }
            - { name: 'edit', icon: 'pencil', label: false }
            - { name: 'delete', icon: 'close', label: false }
    design:
        brand_color: '#ac2925'
        form_theme: 'vertical'
