easy_admin:
    site_name: '%env(APP_NAME)%'
    formats:
        date:     'd-m-Y'
        time:     'H:i'
        datetime: 'd-m-Y H:i:s'
    list:
        max_results: 17
        actions:
            - { name: 'show', icon: 'search', label: false, title: 'Detil' }
            - { name: 'new', icon: 'plus-circle', css_class: 'btn btn-primary action-new', label: false, title: 'Tambah Baru' }
            - { name: 'edit', icon: 'pencil', label: false, title: 'Edit' }
            - { name: 'delete', icon: 'close', label: false, title: 'Hapus' }
    design:
        brand_color: '#ac2925'
        form_theme: 'vertical'
