security:
    encoders:
        KejawenLab\Application\SemartHris\Component\Security\Model\UserInterface: bcrypt
#            algorithm: 'argon2i' #change to argon2i encoder after stable release

    access_decision_manager:
        strategy: unanimous

    role_hierarchy:
        ROLE_EMPLOYEE: ROLE_EMPLOYEE
        ROLE_HRSTAFF: [ROLE_HRSTAFF, ROLE_EMPLOYEE]
        ROLE_HRSUPERVISOR: [ROLE_HRSUPERVISOR, ROLE_HRSTAFF]
        ROLE_HRMANAGER: [ROLE_HRMANAGER, ROLE_HRSUPERVISOR]
        ROLE_HRGENERAL_MANAGER: [ROLE_HRGENERAL_MANAGER, ROLE_HRMANAGER]
        ROLE_HRDIRECTOR: [ROLE_HRDIRECTOR, ROLE_HRGENERAL_MANAGER]
        ROLE_TOP_LEVEL_MANAGEMENT: [ROLE_TOP_LEVEL_MANAGEMENT, ROLE_EMPLOYEE]
        ROLE_SUPER_ADMIN: [ROLE_TOP_LEVEL_MANAGEMENT, ROLE_HRDIRECTOR]

    providers:
        semarthris:
            id: KejawenLab\Application\SemartHris\Security\UserProvider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: semarthris
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true
            guard:
                authenticators:
                    - KejawenLab\Application\SemartHris\Security\Authentication\UsernamePasswordAuthenticator
                    - KejawenLab\Application\SemartHris\Security\Authentication\ApiKeyAuthenticator
                entry_point: KejawenLab\Application\SemartHris\Security\Authentication\UsernamePasswordAuthenticator

    access_control:
