security:
    encoders:
        KejawenLab\Application\SemartHris\Component\Security\Model\UserInterface: bcrypt
#            algorithm: 'argon2i' #change to argon2i encoder after stable release

    role_hierarchy:
        ROLE_EMPLOYEE: ROLE_EMPLOYEE
        ROLE_HRSTAFF: ROLE_HRSTAFF, ROLE_EMPLOYEE]
        ROLE_SUPER_ADMIN: [ROLE_EMPLOYEE]

    providers:
        semarthris:
            id: KejawenLab\Application\SemartHris\Security\UserProvider

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: semarthris
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            anonymous:    true

    access_control:
