vich_uploader:
    db_driver: orm
    mappings:
        profiles:
            uri_prefix: '/files%env(PROFILE_IMAGE_UPLOAD_PATH)%'
            upload_destination: '%kernel.project_dir%%env(UPLOAD_DESTINATION)%%env(PROFILE_IMAGE_UPLOAD_PATH)%'
