vich_uploader:
    db_driver: orm
    mappings:
        profiles:
            uri_prefix: '/files%env(SEMART_PROFILE_IMAGE_UPLOAD_PATH)%'
            upload_destination: '%kernel.project_dir%%env(SEMART_UPLOAD_DESTINATION)%%env(SEMART_PROFILE_IMAGE_UPLOAD_PATH)%'
