###
# This setting is used only in development environment
# The infrastructure is already in production but the application need to be make sure
###
version: '2'
services:
    app:
        build: .
        restart: always
        environment:
            SYMFONY_ENV: dev
            VARNISH_CONFIG: /etc/varnish/default.vcl
            CACHE_SIZE: 512m
            VARNISHD_PARAMS: -p default_ttl=3600 -p default_grace=3600
            VARNISH_PORT: 80
            SEMART_DB_DRIVER: mysql
            SEMART_DB_USER: semarthris
            SEMART_DB_PASSWORD: semarthris
            SEMART_DB_HOST: db
            SEMART_DB_PORT: 3306
            SEMART_DB_NAME: semarthris
        volumes:
            - ./uploads:/semarthris/uploads
        links:
            - db
        depends_on:
            - db

    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_USER: semarthris
            MYSQL_PASSWORD: semarthris
            MYSQL_DATABASE: semarthris
            MYSQL_ROOT_PASSWORD: semarthris
        volumes:
            - ./database:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    balancer:
        image: dockercloud/haproxy:latest
        restart: always
        ports:
            - 8000:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - app
        depends_on:
            - app
