services:
    KejawenLab\Application\SemartHris\Form\DataTransformer\CompanyTransformer:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\CompanyRepository'

    KejawenLab\Application\SemartHris\Form\DataTransformer\DepartmentTransformer:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\DepartmentRepository'

    KejawenLab\Application\SemartHris\Form\DataTransformer\CityTransformer:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\CityRepository'

    KejawenLab\Application\SemartHris\Form\DataTransformer\JobLevelTransformer:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\JobLevelRepository'

    KejawenLab\Application\SemartHris\Form\DataTransformer\JobTitleTransformer:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\JobTitleRepository'

    KejawenLab\Application\SemartHris\Form\DataTransformer\EmployeeTransformer:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'

    KejawenLab\Application\SemartHris\Form\DataTransformer\ContractTransformer:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\ContractRepository'

    KejawenLab\Application\SemartHris\Form\DataTransformer\TagTransformer:

    KejawenLab\Application\SemartHris\Form\DataTransformer\RoleTransformer:
