services:
    KejawenLab\Application\SemartHris\EventListener\DefaultAddressCheckerSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Address\Service\DefaultAddressChecker'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\GenerateUsernameSubscriber:
        arguments:
            - '@security.password_encoder'
            - '@KejawenLab\Application\SemartHris\Component\Security\Service\UsernameGenerator'
            - '%env(APP_DEFAULT_PASSWORD)%'
        tags:
            - { name: 'kernel.event_subscriber' }

    Gedmo\SoftDeleteable\SoftDeleteableListener:
        calls:
            - [ 'setAnnotationReader', [ '@annotation_reader' ] ]
        tags:
            - { name: 'doctrine.event_subscriber', connection: 'default' }
