services:
    KejawenLab\Application\SemartHris\EventListener\DefaultAddressCheckerSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Address\Service\DefaultAddressChecker'
        tags:
            - { name: 'kernel.event_subscriber' }
