services:
    KejawenLab\Application\SemartHris\EventListener\DefaultAddressCheckerSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Address\Service\DefaultAddressChecker'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\GenerateUsernameSubscriber:
        arguments:
            - '@security.password_encoder'
            - '@KejawenLab\Application\SemartHris\Component\User\Service\UsernameGenerator'
            - '%env(APP_DEFAULT_PASSWORD)%'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\UpdateJoinDateFromContractSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\AddCareerHistorySubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Job\Service\AddCareerHistoryService'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\SetOldJobMutationSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\WorkshiftSlicerSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Attendance\Service\WorkshiftSlicer'
            - '@KejawenLab\Application\SemartHris\Repository\WorkshiftRepository'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\MarkUsedContractSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Contract\Service\CheckContractService'
        tags:
            - { name: 'kernel.event_subscriber' }

    Gedmo\SoftDeleteable\SoftDeleteableListener:
        calls:
            - [ 'setAnnotationReader', [ '@annotation_reader' ] ]
        tags:
            - { name: 'doctrine.event_subscriber' }

    Gedmo\Timestampable\TimestampableListener:
        calls:
            - [ 'setAnnotationReader', [ '@annotation_reader' ] ]
        tags:
            - { name: 'doctrine.event_subscriber' }
