services:
    KejawenLab\Application\SemartHris\EventListener\DefaultAddressCheckerSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Address\Service\DefaultAddressChecker'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\GenerateUsernameSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'
            - '@KejawenLab\Application\SemartHris\Security\Service\EncodePasswordService'
            - '@KejawenLab\Application\SemartHris\Component\User\Service\UsernameGenerator'
            - '%env(SEMART_APP_DEFAULT_PASSWORD)%'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\UpdateJoinDateFromContractSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\AddCareerHistorySubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Job\Service\AddCareerHistory'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\SetOldJobMutationSubscriber:
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\WorkshiftSlicerSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Attendance\Service\WorkshiftSlicer'
            - '@KejawenLab\Application\SemartHris\Repository\WorkshiftRepository'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\MarkUsedContractSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Contract\Service\CheckContract'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\AttendanceCalculatorSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Attendance\Service\AttendanceCalculator'
        tags:
            - { name: 'kernel.event_subscriber' }

    KejawenLab\Application\SemartHris\EventListener\OvertimeCalculatorSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Overtime\Service\OvertimeCalculator'
            - '%env(SEMART_OFFDAY_PER_WEEK)%'
        tags:
            - { name: 'kernel.event_subscriber' }

    Gedmo\SoftDeleteable\SoftDeleteableListener:
        calls:
            - [ 'setAnnotationReader', [ '@annotation_reader' ] ]
        tags:
            - { name: 'doctrine.event_subscriber' }

    Gedmo\Timestampable\TimestampableListener:
        calls:
            - [ 'setAnnotationReader', [ '@annotation_reader' ] ]
        tags:
            - { name: 'doctrine.event_subscriber' }
