services:
    KejawenLab\Application\SemartHris\Form\Manipulator\CompanyAddressManipulator:
        arguments:
            - { company: '@KejawenLab\Application\SemartHris\Form\DataTransformer\CompanyTransformer', city: '@KejawenLab\Application\SemartHris\Form\DataTransformer\CityTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveCityTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\DefaultAddressCheckerSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\CompanyDepartmentManipulator:
        arguments:
            - { company: '@KejawenLab\Application\SemartHris\Form\DataTransformer\CompanyTransformer' }

    KejawenLab\Application\SemartHris\Form\Manipulator\EmployeeManipulator:
        arguments:
            - '@KejawenLab\Application\SemartHris\Form\DataTransformer\CompanyTransformer'
            - '@KejawenLab\Application\SemartHris\Form\DataTransformer\JobLevelTransformer'
            - { cityOfBirth: '@KejawenLab\Application\SemartHris\Form\DataTransformer\CityTransformer', department: '@KejawenLab\Application\SemartHris\Form\DataTransformer\DepartmentTransformer', jobTitle: '@KejawenLab\Application\SemartHris\Form\DataTransformer\JobTitleTransformer', supervisor: '@KejawenLab\Application\SemartHris\Form\DataTransformer\EmployeeTransformer', contract: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ContractTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveCityTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveDepartmentTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveJobTitleTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveSupervisorTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveContractTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\PlacementManipulator:
        arguments:
            - { department: '@KejawenLab\Application\SemartHris\Form\DataTransformer\DepartmentTransformer', jobTitle: '@KejawenLab\Application\SemartHris\Form\DataTransformer\JobTitleTransformer', supervisor: '@KejawenLab\Application\SemartHris\Form\DataTransformer\EmployeeTransformer', contract: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ContractTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveDepartmentTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveJobTitleTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveSupervisorTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveContractTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\MutationManipulator:
        arguments:
            - { newDepartment: '@KejawenLab\Application\SemartHris\Form\DataTransformer\DepartmentTransformer', newJobTitle: '@KejawenLab\Application\SemartHris\Form\DataTransformer\JobTitleTransformer', newSupervisor: '@KejawenLab\Application\SemartHris\Form\DataTransformer\EmployeeTransformer', contract: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ContractTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveDepartmentTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveJobTitleTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveSupervisorTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveContractTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\EmployeeAddressManipulator:
        arguments:
            - { employee: '@KejawenLab\Application\SemartHris\Form\DataTransformer\EmployeeTransformer', city: '@KejawenLab\Application\SemartHris\Form\DataTransformer\CityTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveCityTextFieldSubscriber', '@KejawenLab\Application\SemartHris\Form\EventListener\DefaultAddressCheckerSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\ContractManipulator:
        arguments:
            - { tags: '@KejawenLab\Application\SemartHris\Form\DataTransformer\TagTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveTagsTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\ReasonManipulator:
        arguments:
            - []
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\RemoveTypeTextFieldSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\UserManipulator:
        arguments:
            - { roles: '@KejawenLab\Application\SemartHris\Form\DataTransformer\RoleTransformer' }
            - [ '@KejawenLab\Application\SemartHris\Form\EventListener\EncodePasswordSubscriber' ]

    KejawenLab\Application\SemartHris\Form\Manipulator\AttendanceManipulator:
        arguments:
            - { reason: '@KejawenLab\Application\SemartHris\Form\DataTransformer\ReasonTransformer' }
