services:
    KejawenLab\Application\SemartHris\Form\EventListener\RemoveCityTextFieldSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\CityRepository'

    KejawenLab\Application\SemartHris\Form\EventListener\RemoveDepartmentTextFieldSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\DepartmentRepository'

    KejawenLab\Application\SemartHris\Form\EventListener\RemoveJobTitleTextFieldSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\JobTitleRepository'

    KejawenLab\Application\SemartHris\Form\EventListener\RemoveSupervisorTextFieldSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'

    KejawenLab\Application\SemartHris\Form\EventListener\RemoveContractTextFieldSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\ContractRepository'

    KejawenLab\Application\SemartHris\Form\EventListener\DefaultAddressCheckerSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Address\Service\DefaultAddressChecker'

    KejawenLab\Application\SemartHris\Form\EventListener\RemoveTagsTextFieldSubscriber:

    KejawenLab\Application\SemartHris\Form\EventListener\RemoveTypeTextFieldSubscriber:

    KejawenLab\Application\SemartHris\Form\EventListener\RemoveReasonTextFieldSubscriber:

    KejawenLab\Application\SemartHris\Form\EventListener\EncodePasswordSubscriber:
        arguments:
            - '@KejawenLab\Application\SemartHris\Security\Service\PasswordSetter'
