services:
    KejawenLab\Application\SemartHris\Repository\CompanyRepository:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Symfony\Component\HttpFoundation\Session\SessionInterface'
        tags:
            { name: 'semarthris.address_repository' }

    KejawenLab\Application\SemartHris\Repository\CityRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\City']]

    KejawenLab\Application\SemartHris\Repository\DepartmentRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\Department']]

    KejawenLab\Application\SemartHris\Repository\JobTitleRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\JobTitle']]

    KejawenLab\Application\SemartHris\Repository\JobLevelRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\JobLevel']]

    KejawenLab\Application\SemartHris\Repository\EmployeeRepository:
        arguments:
            - '@Doctrine\ORM\EntityManagerInterface'
            - '@Symfony\Component\HttpFoundation\Session\SessionInterface'
        tags:
            { name: 'semarthris.address_repository' }

    KejawenLab\Application\SemartHris\Repository\ContractRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\Contract']]
        tags:
            { name: 'semarthris.contract_repository' }

    KejawenLab\Application\SemartHris\Repository\PlacementRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\Placement']]
        tags:
            { name: 'semarthris.contract_repository' }

    KejawenLab\Application\SemartHris\Repository\CareerHistoryRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\CareerHistory']]

    KejawenLab\Application\SemartHris\Repository\WorkshiftRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\Workshift']]

    KejawenLab\Application\SemartHris\Repository\ShiftmentRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\Shiftment']]

    KejawenLab\Application\SemartHris\Repository\AttendanceRepository:
        calls:
            - ['initialize', ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemartHris\Entity\Attendance']]
