services:
    KejawenLab\Application\SemartHris\Twig\SemartHrisAttendanceTwigExtension:
        lazy: true
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'
            - '@KejawenLab\Application\SemartHris\Repository\ReasonRepository'
            - 'KejawenLab\Application\SemartHris\Entity\Attendance'
        tags:
            - { name: 'twig.extension' }
