services:
    KejawenLab\Application\SemartHris\Validator\UniqueContractValidator:
        lazy: true
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Contract\Service\CheckContract'
        tags:
            { name: 'validator.constraint_validator' }
