# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'id'

services:
    KejawenLab\Application\SemartHris\Component\Address\Repository\AddressRepositoryFactory:
        arguments:
            - ['@KejawenLab\Application\SemartHris\Repository\CompanyRepository', '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository']

    KejawenLab\Application\SemartHris\Component\Address\Service\DefaultAddressChecker:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Address\Repository\AddressRepositoryFactory'

    KejawenLab\Application\SemartHris\Component\Contract\Repository\ContractableRepositoryFactory:
        arguments:
            - ['@KejawenLab\Application\SemartHris\Repository\EmployeeRepository', '@KejawenLab\Application\SemartHris\Repository\PlacementRepository']

    KejawenLab\Application\SemartHris\Component\Contract\Service\CheckContractService:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Contract\Repository\ContractableRepositoryFactory'
            - '@KejawenLab\Application\SemartHris\Repository\ContractRepository'

    KejawenLab\Application\SemartHris\Component\Job\Service\AddCareerHistoryService:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\CareerHistoryRepository'
            - 'KejawenLab\Application\SemartHris\Entity\CareerHistory'

    KejawenLab\Library\PetrukUsername\UsernameFactory:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'
            - ''
            - false

    KejawenLab\Application\SemartHris\Component\Security\Service\UsernameGenerator:
        arguments:
            - '@KejawenLab\Library\PetrukUsername\UsernameFactory'

    KejawenLab\Application\SemartHris\Security\Provider\UserProvider:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'

    KejawenLab\Application\SemartHris\Security\Service\EncodePasswordService:
        arguments:
            - '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface'
