# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'id'
    upload_destination: '%env(UPLOAD_DESTINATION)%'
    workday_per_week: '%env(WORKDAY_PER_WEEK)%'
    offday_per_week: '%env(OFFDAY_PER_WEEK)%'

services:
    KejawenLab\Application\SemartHris\Component\Address\Repository\AddressRepositoryFactory:

    KejawenLab\Application\SemartHris\Component\Address\Service\DefaultAddressChecker:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Address\Repository\AddressRepositoryFactory'

    KejawenLab\Application\SemartHris\Component\Contract\Repository\ContractableRepositoryFactory:

    KejawenLab\Application\SemartHris\Component\Contract\Service\CheckContract:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Contract\Repository\ContractableRepositoryFactory'
            - '@KejawenLab\Application\SemartHris\Repository\ContractRepository'

    KejawenLab\Application\SemartHris\Component\Job\Service\AddCareerHistory:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\CareerHistoryRepository'
            - 'KejawenLab\Application\SemartHris\Entity\CareerHistory'

    KejawenLab\Library\PetrukUsername\UsernameFactory:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'
            - ''
            - false

    KejawenLab\Application\SemartHris\Component\User\Service\UsernameGenerator:
        arguments:
            - '@KejawenLab\Library\PetrukUsername\UsernameFactory'

    KejawenLab\Application\SemartHris\Security\Provider\UserProvider:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'

    KejawenLab\Application\SemartHris\Component\Attendance\Service\WorkshiftSlicer:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\WorkshiftRepository'
            - 'KejawenLab\Application\SemartHris\Entity\Workshift'

    KejawenLab\Application\SemartHris\Component\Attendance\Service\AttendanceCalculator:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\WorkshiftRepository'

    KejawenLab\Application\SemartHris\Security\Service\EncodePasswordService:
        arguments:
            - '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface'

    KejawenLab\Application\SemartHris\Component\Employee\Service\SupervisorChecker:

    KejawenLab\Application\SemartHris\Security\Voter\SupervisorVoter:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Employee\Service\SupervisorChecker'
        tags:
            { name: 'security.voter' }

    KejawenLab\Application\SemartHris\Component\Overtime\Service\OvertimeChecker:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\AttendanceRepository'

    KejawenLab\Application\SemartHris\Component\Overtime\Calculator\HolidayCalculator:
        tags:
            { name: 'semarthris.overtime_calculator' }

    KejawenLab\Application\SemartHris\Component\Overtime\Calculator\WorkdayCalculator:
        tags:
            { name: 'semarthris.overtime_calculator' }

    KejawenLab\Application\SemartHris\Component\Overtime\Calculator\OvertimeCalculator:

    KejawenLab\Application\SemartHris\Component\Overtime\Service\OvertimeCalculator:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Overtime\Service\OvertimeChecker'
            - '@KejawenLab\Application\SemartHris\Component\Overtime\Calculator\OvertimeCalculator'
            - '@KejawenLab\Application\SemartHris\Repository\WorkshiftRepository'
            - '%workday_per_week%'
