# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'id'

services:
    KejawenLab\Application\SemartHris\DependencyInjection\Compiler\AddressFactoryPass:

    KejawenLab\Application\SemartHris\Component\Address\Repository\AddressRepositoryFactory:
        arguments:
            - ['@KejawenLab\Application\SemartHris\Repository\CompanyRepository', '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository']

    KejawenLab\Application\SemartHris\Component\Address\Service\DefaultAddressChecker:
        arguments:
            - '@KejawenLab\Application\SemartHris\Component\Address\Repository\AddressRepositoryFactory'

    KejawenLab\Library\PetrukUsername\UsernameFactory:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'
            - ''
            - false

    KejawenLab\Application\SemartHris\Component\Security\Service\UsernameGenerator:
        arguments:
            - '@KejawenLab\Library\PetrukUsername\UsernameFactory'

    KejawenLab\Application\SemartHris\Security\Provider\UserProvider:
        arguments:
            - '@KejawenLab\Application\SemartHris\Repository\EmployeeRepository'

    KejawenLab\Application\SemartHris\Security\Service\EncodePasswordService:
        arguments:
            - '@Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface'
