# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'id'

services:
    KejawenLab\Application\SemarHris\CompilerPass\ServiceCompilerPassFactory:

    KejawenLab\Application\SemarHris\CompilerPass\AddressFactoryPass:
        tags:
            - { name: 'semarhris.service_compiler' }

    KejawenLab\Application\SemarHris\Component\Address\Repository\AddressRepositoryFactory:
        arguments:
            - ['@KejawenLab\Application\SemarHris\Repository\CompanyRepository']

    KejawenLab\Application\SemarHris\Component\Address\Service\DefaultAddressChecker:
        arguments:
            - '@KejawenLab\Application\SemarHris\Component\Address\Repository\AddressRepositoryFactory'

    KejawenLab\Application\SemarHris\DataTransformer\CompanyTransformer:
        arguments:
            - '@KejawenLab\Application\SemarHris\Repository\CompanyRepository'

    KejawenLab\Application\SemarHris\DataTransformer\CityTransformer:
        arguments:
            - '@KejawenLab\Application\SemarHris\Repository\CityRepository'