# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'id'

services:
    Persona\Hris\Repository\CompanyRepository:
        calls:
            - [initialize, ['@Doctrine\ORM\EntityManagerInterface', '@session']]

    Persona\Hris\DataTransformer\CompanyTransformer:
        arguments:
            - '@Persona\Hris\Repository\CompanyRepository'