# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'id'

services:
    KejawenLab\Application\SemarHris\Repository\CompanyRepository:
        calls:
            - [initialize, ['@Doctrine\ORM\EntityManagerInterface', '@session']]

    KejawenLab\Application\SemarHris\Repository\CityRepository:
        calls:
            - [initialize, ['@Doctrine\ORM\EntityManagerInterface', 'KejawenLab\Application\SemarHris\Entity\City']]

    KejawenLab\Application\SemarHris\DataTransformer\CompanyTransformer:
        arguments:
            - '@KejawenLab\Application\SemarHris\Repository\CompanyRepository'

    KejawenLab\Application\SemarHris\DataTransformer\CityTransformer:
        arguments:
            - '@KejawenLab\Application\SemarHris\Repository\CityRepository'